version: '3'
services:
  app:
    build: .

  # db is is db folder
  world:
    build: world-db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    ports:
      - "33060:3306"