version: '3'
services:
  app:
    build: .

  # db is is db folder
  db:
    build: world-db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    #networks:
    #  - Group11coursework
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "33060:3306"
#networks:
